// Реэкспорт zod-схем и путей из @smeteora/shared.

export {
  productSchema,
  productCategorySchema,
  unitSchema,
  createProductBodySchema,
  updateProductBodySchema,
  listProductsQuerySchema,
  listProductsResponseSchema,
  listBrandsQuerySchema,
  listBrandsResponseSchema,
  createCategoryBodySchema,
  updateCategoryBodySchema,
  listCategoriesResponseSchema,
  listUnitsResponseSchema,
  clearProductsBodySchema,
  clearProductsResponseSchema,
  idParamSchema,
  okResponseSchema,
  CATALOG_SOURCES,
} from '@smeteora/shared';

export type {
  ProductDto,
  ProductCategoryDto,
  UnitDto,
  CreateProductBody,
  UpdateProductBody,
  ListProductsQuery,
  ListProductsResponse,
  ListBrandsQuery,
  ListBrandsResponse,
  CreateCategoryBody,
  UpdateCategoryBody,
  ListCategoriesResponse,
  ListUnitsResponse,
  ClearProductsBody,
  ClearProductsResponse,
  CatalogSource,
} from '@smeteora/shared';
