// Реэкспорт zod-схем контракта из @smeteora/shared.
// Все входы и выходы модуля estimates проходят через эти схемы.

export {
  ESTIMATE_STATUSES,
  ESTIMATE_MODES,
  EXPENSE_CATEGORIES,
  EXPENSE_CATEGORY_LABELS,
  PRICE_BASES,
  VAT_MODES,
  LINE_ITEM_KINDS,
  estimateHeaderSchema,
  estimateSectionSchema,
  estimateLineItemSchema,
  estimateSectionWithTotalsSchema,
  estimateLineItemWithTotalsSchema,
  estimateTreeResponseSchema,
  estimateListItemSchema,
  estimateTotalsSchema,
  listEstimatesQuerySchema,
  listEstimatesResponseSchema,
  createEstimateBodySchema,
  updateEstimateBodySchema,
  upsertTreeBodySchema,
  createLineItemBodySchema,
  updateLineItemBodySchema,
  lineItemIdParamSchema,
  lineItemMutationResponseSchema,
  createSectionBodySchema,
  updateSectionBodySchema,
  sectionIdParamSchema,
  sectionMutationResponseSchema,
  estimateIdParamSchema,
  estimateDeleteResponseSchema,
  ESTIMATES_BASE_PATH,
} from '@smeteora/shared';

export type {
  EstimateStatus,
  EstimateMode,
  ExpenseCategory,
  PriceBasis,
  VatMode,
  LineItemKind,
  EstimateHeader,
  EstimateSectionDto,
  EstimateLineItemDto,
  EstimateTreeResponse,
  EstimateListItem,
  EstimateTotals,
  SectionTotals,
  LineItemTotals,
  ListEstimatesQuery,
  ListEstimatesResponse,
  CreateEstimateBody,
  UpdateEstimateBody,
  UpsertTreeBody,
  TreeSectionInput,
  TreeLineItemInput,
  TreeHeaderPatch,
  CreateLineItemBody,
  UpdateLineItemBody,
  CreateSectionBody,
  UpdateSectionBody,
} from '@smeteora/shared';
